### PR TITLE
Added API key to OpenWeather calls

### PR DESCRIPTION
**Pull request by rladines**

### CODE REVIEW

**Comment by rladines** [comment]
@tomschenkjr @nfspeedypur this should fix #301

**Comment by tomschenkjr** [comment]
@rladines - this isn't the same key that is being used for WindyGrid, right?

**Comment by rladines** [comment]
@tomschenkjr I used the same key for WindyGrid. I did not realize they were different until you asked. Is it ok to switch the keys i.e. use WG's for OpenGrid?

**Comment by tomschenkjr** [comment]
Yeah – do you have the other key?

**Comment by rladines** [comment]
@tomschenkjr yes, I have the other key from the ticket detail

**Comment by tomschenkjr** [comment]
Another conflict with user documentation. Adding @reve0716 to help resolve it.

**Comment by reve0716** [comment]
Tested Open Weather Layers for OG against how it works in WG 
WindyGrid - weather layers all function properly
OpenGrid - weather layers function properly except Cloud Cover (doesn't appear but shows in WindyGrid)

**Comment by tomschenkjr** [comment]
I can also confirm the issue. Below is the console output when trying to view cloud cover:

image

**Pull request merged**
