### PR TITLE
Dev to Master updated doc to have Quick Search documentation

### PR DESCRIPTION
**Pull request by reve0716**
Promoting changes made in the dev branch, updated index file - removed dup paragraph; needs to have quick search documentation promoted to master.

### CODE REVIEW

**Comment by reve0716** [comment]
@nicklucius when you get some time could you promote my changes over into master from dev. I just removed duplicate paragraph, and the quick search documentation needs to be pushed over.

Thanks

**Comment by nicklucius** [comment]
@reve0716 - This PR makes it look like the `dev` is far ahead `master` even though PR #329 seems like it should have brought `master` in line with `dev`. And I checked out the code in `master` and it looks up to date. 

Is there anyone else familiar with the development history of OpenGrid that we could meet with to figure out what happened? There are a few ways to fix this but I'm hesitant to work on it myself since I don't have the background knowledge.

**Comment by tomschenkjr** [comment]
The documentation project has been long-going which has a lot of files being changed in the `docs/` directory. A cursory look seems to show it's all under documentation-related files (nothing with the site). 

@rladines - you may want to double-check the [diff](/files) to make sure no app-related files were touched.

**Comment by nicklucius** [comment]
@rladines - we'd like to get this one approved, could you confirm that no app-related files were touched in this PR? Thank you.

**Comment by rladines** [comment]
@nicklucius I checked the list of files that were changed. All of them look to be documentation-related except for 1 config JS file. That should not impact anything though.

**Pull request merged**
