### PR TITLE
Merge milestone  1.4.0 changes into dev branch

### PR DESCRIPTION
**Pull request by rladines**

### CODE REVIEW

**Comment by rladines** [comment]
@nfspeedypur pls. test the changes with the Plenar.io service layer

**Comment by nfspeedypur** [comment]
Rod,

I will be testing these tonight and over the weekend.  I should have
feedback for Monday.

-David

**Comment by nfspeedypur** [comment]
image



I believe the only issue I have found is in regards to the changes with the new charting.  This charting is using a CreationTimestamp as the X Axis, but this is not supplied by Plenario.  I am overriding this value with the current datetime.

What does this chart look like for WindyGrid. I will say that the donut chart does look the same still.

image

This charting has always been an issue with Plenario, because plenario does not store this kind of custom metadata.  So I can only automatically handle these kind of charts for Zipcodes and wards.

If we are ok with this limitation then I am good with these changes.

**Comment by rladines** [comment]
@nfspeedypur Not sure if you noticed, as part of 1.4.0, there's a new option on the service side to override the default chart options (chart object under options which includes xAxisField and xAxisLabel properties). this will allow you to change the date field to use for the X-Axis, if it does not make sense to use the creation time.

**Comment by nfspeedypur** [comment]
I did not notice that.  I am going to approve this code and I will play with that setting to see if I can find a better X Value.  Overall I do not think this functionality got any worse that before, because we were very limited in the functionality prior to this release.

**Comment by tomschenkjr** [comment]
@rladines - did this also get documents in the new docs?

**Comment by rladines** [comment]
@tomschenkjr are you talking about the API docs? I will update them to reflect 1.4.0 changes before the release.

**Pull request merged**
